image: maven:3.6.2-jdk-11

# stages defined in this pipeline
stages:
  - build
  - deploy  

build:
  stage: build
  script:
    - cd ../core && mvn clean install
    - cd ../modules && mvn clean install
  artifacts:
    paths:
      - deploy/*

deploy_vps:
    stage: deploy
    script:
       - scp -r deploy deploy@${DEV_ENV_IP}:/opt/deploy
       - ssh deploy@${DEV_ENV_IP} "/opt/deploy/deploy.sh"
asd
       
       